fix build on archlinux 'multiple definition of..'
This is because in previous versions of gcc the default of `-fcommon` was changed to `-fno-common`

To fix:
```
$ make
...
/sbin/ld: solver.o:/tmp/cube/src/patterns.h:4: multiple definition of `solved_cube'; cube.o:/tmp/cube/src/operations.h:4: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:340: cube] Error 1
```